### PR TITLE
 add app.js

### PR DESCRIPTION
**Pull request by Git-Hannah**

### CODE REVIEW

**Comment by nikyoto** [comment]
LGTM :)

**Review by nikojuric98 — CHANGES_REQUESTED** [review]
New line missing :P

**Comment by Git-Hannah** [comment]
Gr8 Thx! :o)

**Comment by nikojuric98** [comment]
LGTM now :D

**Review by nikojuric98 — APPROVED** [review]

**Comment by Git-Hannah** [comment]
> LGTM now :D

Awesome! :oD

**Pull request merged**
